version: "3.8"

services:
  mongo:
    image: mongo
    container_name: url_shortner
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo 
      MONGO_INITDB_DATABASE: urlshortner
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
